# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12bjoh1iWPvEQ4zo8Ontac7OG2XrAITtl
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv(r'experience_salary.csv')
df

df.columns

df.shape

df.size

df.head()

df.tail(2)

df.head(2)

df.describe()

"""df.info()"""

from google.colab import files
uploaded = files.upload()

df2 = pd.read_csv(r'restaurants_sample.csv')
df2.head(5)

df2.shape

df2.info()

df2.describe()

from google.colab import files
uploaded = files.upload()

df = pd.read_csv(r'student_scores.csv')
df.head()

df.isnull()

df.isnull().sum()

df.isnull().sum().sum()

df.shape

df1 = df.dropna()
df1

df1.shape

df2 = df.dropna(axis=1)
df2

df.dropna(how = 'any')

df.dropna(how = 'all')

df.dropna(inplace=True)
df

"""FILL IN NULL VALUESMA"""

import pandas as pd
df = pd.read_csv(r'student_scores.csv')

df.isnull().sum()

df.fillna(0)

df.fillna({'Phy': 'Null', 'chem': 0, 'maths': 'shuniya', 'computer': 'null'})
df

df.fillna(method = 'ffill', axis=1)

df['phy'].fillna(value=df['phy'].mean())

df

"""REPLACE

"""

df.head()

df.replace(to_replace=85, value=88)

df.replace(85, 88)

df.replace([85, 82, 90, 95], ['A', 'B', 'C', 'D'])

df.replace('[A-Za-z]', 0, regex=True)

df.replace(to_replace=91, method='ffill')

from google.colab import files
uploaded = files.upload()

df = pd.read_csv(r'student_details.csv', index_col=['rollno'])
df.head()

df.loc[201]

df.iloc[0]

df.iloc[[0, 1, 2]]

df.loc[201, 'phy']

df.loc[201:205, 'chem']

df.loc[df['phy']>50, ['maths']]

"""iloc"""

df.iloc[[0, 1, 2]]

df.iloc[:, 1]

df.iloc[:,:]

branch_group = df.groupby(by='branch')
branch_group

branch_group.groups

df.groupby(by=['branch', 'section'])
branch_group.groups

for group, data_frame in branch_group:
  print(group)
  print(data_frame)



"""#MERGE() Function"""

df1 = pd.DataFrame({'rollno':[1, 2, 3], 'phy': [12, 23, 24]})
df1

df2 = pd.DataFrame({'rollno': [1, 12, 3], 'chem': [22, 33, 44]})
df2

pd.merge(df1, df2, on='rollno')

pd.merge(df1, df2)

pd.merge(df1, df2, how='left')

pd.merge(df1, df2, how='outer')

"""#append() Function"""

import pandas as pd

df1 = pd.DataFrame({'rollno': [1, 2, 3], 'maths': [23, 33, 21], 'phy':[32, 12, 22]})
df2 = pd.DataFrame({'rollno': [4, 5, 6], 'maths': [23, 33, 21], 'phy':[32, 12, 22]})
print(df1)
print(df2)

pd.__version__

pd.concat([df2, df1], ignore_index=True, sort=True)

df1 = pd.DataFrame({'rollno': [1, 2, 3], 'maths': [23, 33, 21], 'phy':[32, 12, 22]})
df2 = pd.DataFrame({'rollno': [4, 5, 6], 'phy':[32, 12, 22]})
print(df1)
print(df2)

pd.concat([df2, df1], ignore_index=True)

df = pd.read_csv(r'student_details.csv')
df.head()

pd.pivot_table(df, index='branch')

pd.pivot_table(df, index='branch', columns='section')